### ISSUE TITLE
Screenshots taken in a single tick

### ISSUE THREAD

**Issue by credomane** [credomane/CredoTimeLapseMod#2]
Taking all screenshots in a single tick will continue to make a larger and large single lag spike as the number of screenshots grow.

Need to break screenshots up over a period of say 300 ticks (~5 seconds)

**Comment by credomane** [comment]
Might change this one to a wontfix. While working on #1 the many mini lag spikes became annoying while a single long one wasn't any worse than the autosave every 2 minutes.

**Comment by ghost** [comment]
could change to a setting
