### ISSUE TITLE
Factorissimo2 Compatibility

### ISSUE THREAD

**Issue by j2ghz** [credomane/CredoTimeLapseMod#8]
Positional screenshots don't work very well right now with Factory buidlings from [Factorissimo2](https://mods.factorio.com/mods/MagmaMcFry/Factorissimo2). Right now the workaround is to just delete the small pngs, since the screenshot inside is mostly black (48kB vs 4,5MB).

Ideas:
1. Notify a predefined amount of time before taking a screenshot, so the user can go outside
1. When inside a Factory building, don't take the screenshot
1. When inside a Factory building, don't take the screenshot, but check every 1/10th of the interval if user is still inside
1. When inside a Factory building, don't take the screenshot, but take it as soon as the user goes outside
1. Take the screenshot of outside even when inside

I ordered them from least to most helpful, since I have no idea what technical limitations are there, or how hard to implement those would be.

**Comment by credomane** [comment]
\*Scratches head\*
I noticed this with the original Factorissimo a long time ago. I fixed this or so I thought. I even made [this forum post](https://forums.factorio.com/27196) asking for the ability to choose what surface in the screenshot function itself.

The fix I did is no where in the code or the git history. I'll fix this again or perhaps for the first time? I'm so confused right now. lol

What I originally [thought I] did was:

- Check the player's current surface
- If correct surface take the screenshot(s)
- If wrong surface warn player with `[CTLM] You are not on the surface "{insert surface}. Will wait up to {screenshot_timer/5} seconds for you to move to that surface before skipping screenshot."` Warning will get an internal 120 game seconds cooldown to prevent spam if the screenshot interval is short enough. Plus that makes missing screenshot mostly insignificant anyways.
- If success or failure of screenshot notify player if {Print screenshots messages} enabled.

**Comment by credomane** [comment]
This issue is naturally resolved with Factorio 0.16. I'm going to close it. If it still isn't working properly reopen the issue and I will look into it further.

Also at the time of this comment the mod portal won't accept mod uploads. Grab the release manually from [here](https://github.com/credomane/FactorioMods_CredoTimeLapseMod/releases/latest).
