### ISSUE TITLE
LuaGuiElement with name "enabled" no longer permitted

### ISSUE THREAD

**Issue by narc0tiq** [credomane/CredoTimeLapseMod#9]
Reference: https://www.reddit.com/r/factorio/comments/6idye5/_/dj5gnqy/

I think the patch in my comment is sufficient, but (as I said there), I haven't tested it. Good luck!

**Comment by credomane** [comment]
Thanks. I don't play for a bit and my stuff gets broken. lol

I had "enabled" used for a element name in three places. I got em all fixed up in V0.15.9.
